### ISSUE TITLE
Accompanying paper

### ISSUE THREAD

**Issue by sgbaird** [kaaiian/CBFV#4]
What is the paper that accompanies this? Maybe include in the README?

**Comment by anthony-wang** [comment]
@sgbaird as far as I know, there is not an explicit publication that accompanies this GitHub repo.
However there are several works that use this (sorted by year):

Wang, A.YT., Kauwe, S.K., Murdock, R.J. et al. Compositionally restricted attention-based network for materials property predictions. npj Comput Mater 7, 77 (2021). https://doi.org/10.1038/s41524-021-00545-1

Murdock, R.J., Kauwe, S.K., Wang, A.YT. et al. Is Domain Knowledge Necessary for Machine Learning Materials Properties?. Integr Mater Manuf Innov 9, 221–227 (2020). https://doi.org/10.1007/s40192-020-00179-z

Clement, C.L., Kauwe, S.K. & Sparks, T.D. Benchmark AFLOW Data Sets for Machine Learning. Integr Mater Manuf Innov 9, 153–156 (2020). https://doi.org/10.1007/s40192-020-00174-4

Kauwe, S. K., Graser, J., Murdock, R., & Sparks, T. D. (2020). Can machine learning find extraordinary materials? Computational Materials Science, 174, 109498. https://doi.org/10.1016/j.commatsci.2019.109498

Wang, A. Y.-T., Murdock, R. J., Kauwe, S. K., Oliynyk, A. O., Gurlo, A., Brgoch, J., Persson, K. A., & Sparks, T. D. (2020). Machine Learning for Materials Scientists: An Introductory Guide toward Best Practices. Chemistry of Materials, 32(12), 4954–4965. https://doi.org/10.1021/acs.chemmater.0c01907

Kauwe, S.K., Graser, J., Vazquez, A. et al. Machine Learning Prediction of Heat Capacity for Solid Inorganics. Integr Mater Manuf Innov 7, 43–51 (2018). https://doi.org/10.1007/s40192-018-0108-9

Disclaimer: I may have missed some others; these are the publications I could think of thus far that use this package.

**Comment by sgbaird** [comment]
Given how many papers use this and the general usefulness for a lot of materials researchers, it might be worth doing a JOSS submission for CBFV.
